### ISSUE TITLE
make compile: python traceback "TypeError: argument 'data': 'bytearray' object cannot be converted to 'PyBytes'"

### ISSUE THREAD

**Issue by sanderjo** [skiffos/SkiffOS#204]
I followed https://github.com/skiffos/SkiffOS/tree/master/configs/allwinner/licheerv on my Ubuntu 20.04 NUC, and bumped into the python traceback below. AFAIK the Ubuntu install is quite clean, but it could be dirty install or PEBKAC. 
I will try on my very fresh Ubuntu 22.04 install.

Anyway: the python traceback:

```
Traceback (most recent call last):
  File "/home/sander/git/SkiffOS/workspaces/default/build/ca-certificates-20211016/mozilla/certdata2pem.py", line 125, in <module>
    cert = x509.load_der_x509_certificate(obj['CKA_VALUE'])
  File "/home/sander/.local/lib/python3.10/site-packages/cryptography/x509/base.py", line 443, in load_der_x509_certificate
    return rust_x509.load_der_x509_certificate(data)
TypeError: argument 'data': 'bytearray' object cannot be converted to 'PyBytes'
```
python3.10? Weird. That points towards a dirty install on my side ...

A bit more context:

```
git clone https://github.com/skiffos/SkiffOS.git
cd SkiffOS/
export SKIFF_CONFIG=allwinner/licheerv,core/alpine
make configure

sander@brixit:~/git/SkiffOS$ make compile
...
Certificate "TURKTRUST Mis-issued Intermediate CA 1" blacklisted, ignoring.
Certificate "TURKTRUST Mis-issued Intermediate CA 2" blacklisted, ignoring.
Ignoring certificate "Staat der Nederlanden Root CA - G3".  SAUTH=CKT_NSS_MUST_VERIFY_TRUST, EPROT=CKT_NSS_TRUSTED_DELEGATOR
Ignoring certificate "Symantec Class 1 Public Primary Certification Authority - G6".  SAUTH=CKT_NSS_MUST_VERIFY_TRUST, EPROT=CKT_NSS_TRUSTED_DELEGATOR
Ignoring certificate "Symantec Class 2 Public Primary Certification Authority - G6".  SAUTH=CKT_NSS_MUST_VERIFY_TRUST, EPROT=CKT_NSS_TRUSTED_DELEGATOR
Ignoring certificate "D-TRUST Root CA 3 2013".  SAUTH=CKT_NSS_MUST_VERIFY_TRUST, EPROT=CKT_NSS_TRUSTED_DELEGATOR
Ignoring certificate "GlobalSign Secure Mail Root R45".  SAUTH=CKT_NSS_MUST_VERIFY_TRUST, EPROT=CKT_NSS_TRUSTED_DELEGATOR
Ignoring certificate "GlobalSign Secure Mail Root E45".  SAUTH=CKT_NSS_MUST_VERIFY_TRUST, EPROT=CKT_NSS_TRUSTED_DELEGATOR
Traceback (most recent call last):
  File "/home/sander/git/SkiffOS/workspaces/default/build/ca-certificates-20211016/mozilla/certdata2pem.py", line 125, in <module>
    cert = x509.load_der_x509_certificate(obj['CKA_VALUE'])
  File "/home/sander/.local/lib/python3.10/site-packages/cryptography/x509/base.py", line 443, in load_der_x509_certificate
    return rust_x509.load_der_x509_certificate(data)
TypeError: argument 'data': 'bytearray' object cannot be converted to 'PyBytes'
make[5]: *** [Makefile:6: all] Error 1
make[4]: *** [Makefile:9: all] Error 2
make[3]: *** [package/pkg-generic.mk:293: /home/sander/git/SkiffOS/workspaces/default/build/ca-certificates-20211016/.stamp_built] Error 2
make[2]: *** [Makefile:23: _all] Error 2
make[2]: Leaving directory '/home/sander/git/SkiffOS/workspaces/default'
make[1]: *** [Makefile:64: compile] Error 2
make[1]: Leaving directory '/home/sander/git/SkiffOS/build'
make: *** [Makefile:2: compile] Error 2
```

**Comment by sanderjo** [comment]
... a PEBKAC / dirty install on my side: removed python3.10 and packages, and compile now proceeds
